name: fitflow
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  table_calendar: ^3.0.9 
  fl_chart: ^0.64.0
  intl: ^0.18.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  week_of_year: ^2.0.2
  video_player: ^2.8.6

  # Local Database (Persistence)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # Functionality
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  android: true
  ios: false # We are only building for Android
  image_path: "assets/icon/icon.png"



flutter:
  uses-material-design: true
