name: fitflow
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0
  table_calendar: ^3.0.9 
  fl_chart: ^0.64.0
  intl: ^0.18.1

  # Functionality (optional for now, but good to have)
  image_picker: ^1.0.4
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
